select 'TABLE_CONSTRAINTS', * from INFORMATION_SCHEMA.TABLE_CONSTRAINTS
select 'CONSTRAINT_TABLE_USAGE', * from INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE
select 'CONSTRAINT_COLUMN_USAGE', * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
select 'KEY_COLUMN_USAGE', * from INFORMATION_SCHEMA.KEY_COLUMN_USAGE
select * from INFORMATION_SCHEMA.KEY_COLUMN_USAGE

/*
select * from INFORMATION_SCHEMA.CHECK_CONSTRAINTS
select * from INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
*/